BEM exercise implementation
Lily-Lilian/BEM3-Saas pull request #1
Opened 2022-10-11 12:31 UTC by Lily-Lilian

2022-10-12 08:58 UTC, rithaven commented on home.html
> +      <nav class="navbar">
Block inside another, it is not good practice in BEM(from Yannick). you should write "header__navbar"

2022-10-12 09:02 UTC, rithaven commented on home.html
> +            class="discover-section_image"
Typo error. change it to double underscore

2022-10-12 09:03 UTC, rithaven commented on home.html
> +        <li class="discover-section_item">
Here also. "__"

2022-10-12 09:03 UTC, ritha-kankindi commented on home.html
> +          <div class="discover-section_contents">
Here also

2022-10-12 09:03 UTC, ritha-kankindi commented on home.html
> +            <h1 class="discover-section_title">Activity Report</h1>
Here also "__"

2022-10-12 09:04 UTC, rithaven commented on home.html
> +          <img src="./Assets/Images/Icon@2x.png" alt="images " />
This image should have a class name

2022-10-12 09:07 UTC, ritha-kankindi commented on home.html
> +                  class="avatar"
This image should have a class name according to it's block name

2022-10-12 09:07 UTC, rithaven commented on home.html
> +                  src="./assets/Images/photography-of-a-guy-wearing-green-shirt-1222271.svg"
Here also

2022-10-12 09:08 UTC, rithaven commented on home.html
> +</html>
Good job! You are almost done

2022-10-12 15:40 UTC, rithaven approved these changes

2022-10-13 09:20 UTC, sezeranoJchrisostome requested changes
Well done @Lily-Lilian, I left some comments for you, you may check them out please

2022-10-13 09:20 UTC, chrisostome01 commented on home.html
> +            <li class="header__navbar-item"><a href="home.html"> Home</a></li>
your link tag here should have a class

2022-10-13 09:20 UTC, chrisostome01 commented on home.html
> +              <div>
This div should have class name

2022-10-13 09:20 UTC, chrisostome01 commented on home.html
> +              <button class="button button--primary">Subscribe</button>
here Would you relate this btn to its parent

2022-10-13 09:20 UTC, chrisostome01 commented on home.html
> +          <p class="pt-9">© Copyright Finsweet 2022</p>
This is the tailwind class name, you change it to this block's element

2022-10-13 09:20 UTC, chrisostome01 commented on product.html
> +      <div class="some-thesis">
Block names should be meaningful, try to improve this block name

2022-10-13 09:20 UTC, chrisostome01 commented on product.html
> +            width="616px"
inline style is not recommended, its better you put it inside the CSS file and control it there

2022-10-13 09:20 UTC, chrisostome01 commented on product.html
> +            width="466.98px"
same here

2022-10-13 09:20 UTC, chrisostome01 commented on product.html
> +            src="./Assets/Images/client2.png"
same here

2022-10-13 09:20 UTC, chrisostome01 commented on product.html
> +            class="clint-layout__image"
this client is out its parent block

2022-10-13 09:20 UTC, chrisostome01 commented on product.html
> +            <h2 class="gradient-title gradient-title--sm">
Would you follow the BEM structure here by relating this to its block parent

2022-10-13 09:20 UTC, sezeranoJchrisostome commented on product.html
> +            <h2 class="gradient-title gradient-title--sm">
relate this to it's parent too

2022-10-13 09:20 UTC, sezeranoJchrisostome commented on product.html
> +          <img
This image does not have class

2022-10-13 09:20 UTC, sezeranoJchrisostome commented on product.html
> +            height="448px"
avoid applying you style by inline

2022-10-13 09:20 UTC, sezeranoJchrisostome commented on product.html
> +            <h2 class="gradient-title gradient-title--sm">
same here relate this to its parent

2022-10-13 09:20 UTC, sezeranoJchrisostome commented on product.html
> +          <h1 class="description">
relate this to it's block also

2022-10-13 09:20 UTC, sezeranoJchrisostome commented on product.html
> +        <div class="flex gap-6">
use bem here not tailwind

2022-10-13 09:20 UTC, sezeranoJchrisostome commented on product.html
> +          <p class="pt-9">© Copyright Finsweet 2022</p>
same here

2022-10-13 09:20 UTC, chrisostome01 commented on product.html
> +            <div class="footer__socials flex items-center">
same here

2022-10-13 11:15 UTC, chrisostome01 approved these changes

2022-10-20 12:02 UTC, Morrism1 requested changes
Few changes requested!

2022-10-20 12:02 UTC, Morrism1 commented on home.html
> +    <div class="impression-layout__logos">
`impression-layout__logos` is positioned outside the Block `impression-layout`. If you want to make it a block name it the right way.

2022-10-20 12:02 UTC, Morrism1 commented on home.html
> +    <div class="impression-layout__logos">
Also, remember to change it to all the children

2022-10-20 12:02 UTC, Morrism1 commented on home.html
> +                <h1 class="testimony__name">Roon Wood</h1>
Here you used a block called `testimony` while the name for the block above is `testimony-layout` if you want it, create it or use the existing one.

2022-10-20 12:02 UTC, Morrism1 commented on home.html
> +                <p class="testimony__job">CEO</p>
Same thing here!

2022-10-20 12:02 UTC, Morrism1 commented on home.html
> +                <h1 class="testimony__name">Roon Wood</h1>
Also here!

2022-10-20 12:02 UTC, Morrism1 commented on home.html
> +                <p class="testimony__job">CEO</p>
Also here!

2022-10-20 12:02 UTC, Morrism1 commented on home.html
> +              <h1 class="testimony__name">Roon Wood</h1>
Also here!

2022-10-20 12:02 UTC, Morrism1 commented on home.html
> +              <p class="testimony__job">CEO</p>
Also here!

2022-10-20 12:02 UTC, Morrism1 commented on pricing.html
> +        <div class="pricing-section__card">
I think you meant to use `price-section` block here instead of `pricing-section` and also remember to change it in all children below

2022-10-20 12:02 UTC, Morrism1 commented on pricing.html
> +        <div class="frequent__container">
Here you are using a BLOCK `frequent` and it's not defined anywhere as a BLOCK you have above is `frequent-section` and change it in all below elements too.

2022-10-20 12:02 UTC, Morrism1 commented on pricing.html
> +              <div class="questions__content">
Same issue here for `questions` BLOCK is not defined but is used.

2022-10-20 12:02 UTC, Morrism1 commented on pricing.html
> +              <div class="questions__content">
Remember to change it in the below elements too!

2026-06-13 13:00 UTC, closed without merging